FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY apps/realtime/go.mod ./
# If go.sum exists copy it, else download deps
RUN go mod tidy

COPY apps/realtime ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /server cmd/server/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /server ./server

EXPOSE 8080
CMD ["./server"]
